services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: oil-checker-php
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./:/srv/app
        networks:
            - oil
    
    caddy:
        image: caddy:2.7-alpine
        container_name: caddy
        depends_on:
            - php
        restart: unless-stopped
        ports:
            - "8383:80"
        volumes:
            - ./caddy:/etc/caddy
        networks:
            - oil

networks:
    oil:
        driver: bridge
